# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit report.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE)

library(plotly)
library(ggplot2)
library(kableExtra)
library(microbenchmark)



## ----auc-gini, fig.align = "center", out.width = "100%", fig.cap="Geometric interpretation. The black piecewise linear curve represents the receiver operating characteristic (ROC) curve. The AUC (also referred to as AUROC, ROC score, C-statistic, or Vargha–Delaney A) is defined as the area under the ROC curve. A linear transformation of the AUC—known, among others, as the Gini coefficient, Cliff’s delta, Somers’ D, or the ROC skill score—equals twice the area between the diagonal line y=x and the ROC curve. ", dev=if(knitr::is_latex_output()) "cairo_pdf" else "png"----
cz = c(.2, .42, .6, .7, .8, .88, .95, .99)
sw = c(.98, .95, .9, .86, .8, .72, .6, .4)

df <- data.frame(FPR = c(0, 1-sw, 1), TPR = c(0, cz, 1))

library(ggplot2)
library(patchwork)

ggplot(df, aes(x = FPR, y = TPR)) +
  annotate("rect", xmin = 0, xmax = 1, ymin = 0, ymax = 1, fill = "white", color = "black") +
  geom_area(fill="lightblue") +
  geom_line() +
  geom_point() +
  annotate("text", x = 0.5, y = 0.5, label = "AUC", size =10,  color = "darkblue") +
  coord_fixed(ratio = 1, xlim = c(0,1), ylim = c(0,1)) +
  labs(x = "FPR (1 - specificity)", 
       y = "TPR (sensitivity)") +
  theme_minimal() +

#library(ggplot2)
ggplot(df, aes(x = FPR, y = TPR)) +
  annotate("rect", xmin = 0, xmax = 1, ymin = 0, ymax = 1, fill = "white", color = "black") +
  geom_polygon(fill="orange2") +
  geom_polygon(aes(x=TPR, y=FPR), fill="orange1") +
  geom_line() +
  geom_point() +
  annotate("text", x = 0.5, y = 0.5, label = "“Gini”", size =10,  color = "orange4") +
  coord_fixed(ratio = 1, xlim = c(0,1), ylim = c(0,1)) +
  labs(x = "FPR (1 - specificity)", y = "") +
  theme_minimal()


## -----------------------------------------------------------------------------
ftl <- read.csv("../data/functions_table.csv", sep = ";")

fth <- as.data.frame(lapply(ftl, function(x) {
  x %>%
    gsub("\\$", "\\\\$", .) %>%
    gsub("@", "\\\\@", .)
  }))

if (knitr::is_latex_output()) {
  knitr::kable(ftl, format = "latex", booktabs = TRUE, linesep = "\\addlinespace",
               caption = "Functions computing AUC.") %>%
    kable_styling(latex_options = c("HOLD_position", "scale_down")) %>%
    column_spec(3, monospace = TRUE)
} else {
  knitr::kable(fth, format = "html",
             caption = "Functions computing AUC.") %>%
    kable_styling(bootstrap_options = "condensed") %>%
    column_spec(3, width_min = "33em", width_max = "33em", monospace = TRUE) %>%
    column_spec(4, width_min = "9em", width_max = "9em")
}


## ----setting up for package benchmarks, include = FALSE-----------------------
plot_benchmark <- function(benchmark) {
  autoplot(benchmark) +
    theme(axis.text.y = element_text(size = rel(1.5)))
}

package_benchmark1 <- readRDS("../data/packages_benchmark_1.rds")
package_benchmark2 <- readRDS("../data/packages_benchmark_2.rds")
package_benchmark3 <- readRDS("../data/packages_benchmark_3.rds")



## ----package_benchmark_1, fig.align="center", out.width="100%"----------------
plot_benchmark(package_benchmark1)



## ----package_benchmark_2, fig.align="center", out.width="100%"----------------
plot_benchmark(package_benchmark2)



## ----package_benchmark_3, fig.align="center", out.width="100%"----------------
plot_benchmark(package_benchmark3)



## ----setup for own function benchmarks, include = FALSE-----------------------
own_functions_benchmark1 <- readRDS("../data/own_functions_benchmark_1.rds")
own_functions_benchmark2 <- readRDS("../data/own_functions_benchmark_2.rds")
own_functions_benchmark3 <- readRDS("../data/own_functions_benchmark_3.rds")



## ----own_function_benchmark_1, fig.align="center", out.width="100%"-----------
plot_benchmark(own_functions_benchmark1)


## ----own_function_benchmark_2, fig.align="center", out.width="100%"-----------
plot_benchmark(own_functions_benchmark2)


## ----own_function_benchmark_3, fig.align="center", out.width="100%"-----------
plot_benchmark(own_functions_benchmark3)

