# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit report.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(plotly)
library(ggplot2)
library(kableExtra)
library(readr)
library(Rcpp)
library(microbenchmark)
library(reticulate)

#sourceCpp("../scripts/AUC_cpp.cpp")
#source("../R/AUC_functions.R")
#use_python(Sys.which("python"), required = TRUE)
#roc_auc_score <- import("sklearn.metrics")$roc_auc_score


## ----auc-gini, fig.align = "center", out.width = "100%", fig.cap="Geometric interpretation: AUC (AUROC) is the area under the ROC curve, Gini is twice the area between the diagonal y=x and the ROC curve.", dev=if(knitr::is_latex_output()) "cairo_pdf" else "png"----
cz = c(.6, .8, .95)
sw = c(.9, .8, .6)

df <- data.frame(FPR = c(0, 1-sw, 1), TPR = c(0, cz, 1))

library(ggplot2)
library(patchwork)

ggplot(df, aes(x = FPR, y = TPR)) +
  annotate("rect", xmin = 0, xmax = 1, ymin = 0, ymax = 1, fill = "white", color = "black") +
  geom_area(fill="lightblue") +
  geom_line() +
  geom_point() +
  annotate("text", x = 0.5, y = 0.5, label = "AUC", size =10,  color = "darkblue") +
  coord_fixed(ratio = 1, xlim = c(0,1), ylim = c(0,1)) +
  labs(x = "FPR (1 - specificity)\ncumulative fraction of goods", 
       y = "TPR (sensitivity)\ncumulative fraction of bads") +
  theme_minimal() +

#library(ggplot2)
ggplot(df, aes(x = FPR, y = TPR)) +
  annotate("rect", xmin = 0, xmax = 1, ymin = 0, ymax = 1, fill = "white", color = "black") +
  geom_polygon(fill="orange2") +
  geom_polygon(aes(x=TPR, y=FPR), fill="orange1") +
  geom_line() +
  geom_point() +
  annotate("text", x = 0.5, y = 0.5, label = "Gini", size =10,  color = "orange4") +
  coord_fixed(ratio = 1, xlim = c(0,1), ylim = c(0,1)) +
  labs(x = "FPR (1 - specificity)\ncumulative fraction of goods", y = "") +
  theme_minimal()


## -----------------------------------------------------------------------------
functions_table <- read.csv("../functions_table.csv", sep = ";")

kable(functions_table, caption = "Table 1: Functions computing AUC.") %>%
  kable_styling(font_size = 7)


## -----------------------------------------------------------------------------
# First dataset (n = 1000)

pred1 <- c(rnorm(500), rnorm(500, 1))

target1 <- c(rep(1, 500), rep(0, 500))

# Second dataset (n = 10000)

pred2 <- c(rnorm(5000), rnorm(5000, 1))

target2 <- c(rep(1, 5000), rep(0, 5000))

# Third dataset (n = 100000)

pred3 <- c(rnorm(50000), rnorm(50000, 1))

target3 <- c(rep(1, 50000), rep(0, 50000))


call_benchmark <- function(pred, target, times = 100) {
  
  my_benchmark <- microbenchmark(
    
    ROCR::performance(ROCR::prediction(-pred, target), "auc")@y.values[[1]],
    
    pROC::auc(target, pred, lev=c('0', '1'), dir=">"),
    
    mltools::auc_roc(-pred, target),
    
    Hmisc::somers2(-pred, target)["C"],
    
    bigstatsr::AUC(-pred, target),
    
    scorecard::perf_eva(-pred, target, binomial_metric = "auc", show_plot = FALSE)$binomial_metric$dat$AUC,
    
    caTools::colAUC(-pred, target)[1, 1],
    
    precrec::evalmod(precrec::mmdata(scores = -pred, labels = target), mode = "aucroc")$uaucs$aucs,
    
    roc_auc_score(target, -pred),
    
    yardstick::roc_auc_vec(as.factor(target), pred),
    
    (rcompanion::cliffDelta(x = pred[target == 0], y = pred[target == 1], digits = 100) + 1) / 2,
    
    ModelMetrics::auc(target, -pred),
    
    MLmetrics::AUC(-pred, target),
    
    cvAUC::AUC(-pred, target),
    
    fbroc::boot.roc(-pred, as.logical(target))$auc,
    
    DescTools::Cstat(-pred, target),
    
    effsize::VD.A(pred ~ factor(target))$estimate,
    
    rcompanion::vda(x = pred[target == 0], y = pred[target == 1], digits=100),
    
    times = times
  )
  
  levels(my_benchmark$expr) <- c("ROCR", "pROC",
                                 "mltools", "Hmisc", "bigstatsr", "scorecard",
                                 "caTools", "precrec", "scikit-learn",
                                 "yardstick", "rcompanion::cliffDelta", "ModelMetrics", "MLmetrics",
                                 "cvAUC", "fbroc", "DescTools", "effsize", "rcompanion::vda"
                                 )
  
  my_benchmark$expr <- reorder(my_benchmark$expr, -my_benchmark$time, FUN = median)
  
  autoplot(my_benchmark) +
    theme(axis.text.y = element_text(size = rel(1.5)))
}




## -----------------------------------------------------------------------------
#call_benchmark(pred1, target1)



## -----------------------------------------------------------------------------
#call_benchmark(pred2, target2)



## -----------------------------------------------------------------------------
#call_benchmark(pred3, target3)


